# Generated by Django 4.1.5 on 2023-02-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='passmodel',
            fields=[
                ('aadhar', models.IntegerField(max_length=12, primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=70)),
                ('gender', models.CharField(max_length=11)),
                ('contact', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=6)),
                ('dob', models.DateField(max_length=10)),
            ],
        ),
    ]
