# Generated by Django 4.1.5 on 2023-02-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_passmodel_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passmodel',
            name='dob',
            field=models.DateField(),
        ),
    ]
