# Generated by Django 4.1.5 on 2023-02-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_passmodel_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passmodel',
            name='contact',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='passmodel',
            name='pin',
            field=models.IntegerField(),
        ),
    ]
